apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-replicaset
  labels:
    app: my-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-backend
  template:
    metadata:
      labels:
        app: my-backend
    spec:
      containers:
      - name: backend
        image: tpsribeirao/backend:latest
        ports:
        - containerPort: 8080
